language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t yosuke65/docker-travisci-aws-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true yosuke65/docker-travisci-aws-demo npm run test